apiVersion: batch/v1
kind: Job
metadata:
  name: replacer-secret-create-dev
spec:
  template:
    metadata:
      name: replacer-secret-create-dev
    spec:
      containers:
      - args:
        - create
        - --host=replacer,replacer.$(POD_NAMESPACE).svc
        - --namespace=$(POD_NAMESPACE)
        - --secret-name=replacer-secret-dev
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: lank8s.cn/ingress-nginx/kube-webhook-certgen:v1.1.1
        imagePullPolicy: IfNotPresent
        name: create
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
      serviceAccountName: replacer-dev
---
apiVersion: batch/v1
kind: Job
metadata:
  name: replacer-secret-patch-dev
spec:
  template:
    metadata:
      name: replacer-secret-patch-dev
    spec:
      volumes:
      - secret:
          secretName: replacer-secret-dev
        name: tlsfile
      containers:
      - name: patch
        args:
        - patch
        - --webhook-name=replacer-webhook-dev
        - --namespace=$(POD_NAMESPACE)
        - --patch-mutating=true
        - --patch-validating=false
        - --secret-name=replacer-secret-dev
        - --patch-failure-policy=Fail
        volumeMounts:
        - name: tlsfile
          mountPath: /tlsfile/
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: lank8s.cn/ingress-nginx/kube-webhook-certgen:v1.1.1
        imagePullPolicy: IfNotPresent
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
      serviceAccountName: replacer-dev