apiVersion: apps/v1
kind: Deployment
metadata:
  name: replacer
  labels:
    app: replacer
spec:
  selector:
    matchLabels:  
      app: replacer
  replicas: 1
  template:
    metadata:
      labels:
        app: replacer
    spec:
      volumes:
      - secret:
          secretName: replacer
        name: tlsfile
      serviceAccountName: replacer
      initContainers:
        - name: waitfor
          image: ghcr.io/liangyuanpeng/waitfor:v1.0.0
          imagePullPolicy: IfNotPresent
          args:
          - --jobname 
          - replacer-patch
      containers:
        - name: replacer
          image: ghcr.io/liangyuanpeng/replacer:v1.0.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: tlsfile
            mountPath: /tlsfile/
          args:
          - --cert=/tlsfile/cert
          - --key=/tlsfile/key
          ports:
            - name: replacer
              protocol: TCP
              containerPort: 8181
          resources:
            requests:
              memory: 125Mi 
            limits:
              memory: 512Mi

---
