apiVersion: v1
kind: ServiceAccount
metadata:
  name: replacer
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: replacer
  namespace: default
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingWebhookConfigurations
  verbs:
  - list
  - get
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  - service
  verbs:
  - list
  - create
  - update
  - get
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: replacer
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingWebhookConfiguration
  - mutatingwebhookconfigurations
  verbs:
  - "*"
- apiGroups:
  - "*"
  resources:
  # - mutatingWebhookConfiguration
  # - mutatingWebhookConfigurations
  - secrets
  verbs:
  - "*"
# - apiGroups:
#   - admissionregistration.k8s.io
#   resources:
#   - mutatingWebhookConfigurations
#   verbs:
#   - list
#   - get
#   - update
#   - patch
# - apiGroups:
#   - apps
#   resources:
#   - daemonsets
#   verbs:
#   - create
#   - patch
#   - update
#   - watch
# - apiGroups:
#   - apps
#   resources:
#   - deployments
#   verbs:
#   - get
#   - list
#   - create
#   - patch
#   - update
#   - watch
# - apiGroups:
#   - ""
#   resources:
#   - pods
#   - secrets
#   - service
#   verbs:
#   - list
#   - create
#   - update
#   - get
#   - patch
---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: replacer
#   namespace: default
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: Role
#   name: replacer
# subjects:
# - kind: ServiceAccount
#   name: replacer
#   namespace: default
# ---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: replacer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: replacer
subjects:
- kind: ServiceAccount
  name: replacer
  namespace: default
---