apiVersion: batch/v1
kind: Job
metadata:
  name: replacer-create
spec:
  template:
    metadata:
      name: replacer-create
    spec:
      containers:
      - args:
        - create
        - --host=replacer,replacer.$(POD_NAMESPACE).svc
        - --namespace=$(POD_NAMESPACE)
        - --secret-name=replacer
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: lank8s.cn/ingress-nginx/kube-webhook-certgen:v1.1.1
        imagePullPolicy: IfNotPresent
        name: create
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
      serviceAccountName: replacer
---
apiVersion: batch/v1
kind: Job
metadata:
  name: replacer-patch
spec:
  template:
    metadata:
      name: replacer-patch
    spec:
      # initContainers:
      # - name: init
      #   image: cfssl/cfssl:1.6.1 
      #   imagePullPolicy: IfNotPresent
      #   command: ["sh","-c","sleep 99999"]
      volumes:
      - secret:
          secretName: replacer
        name: tlsfile
      containers:
      - name: patch
        args:
        - patch
        - --webhook-name=replacer
        - --namespace=$(POD_NAMESPACE)
        - --patch-mutating=true
        - --patch-validating=false
        - --secret-name=replacer
        - --patch-failure-policy=Fail
        volumeMounts:
        - name: tlsfile
          mountPath: /tlsfile/
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: lank8s.cn/ingress-nginx/kube-webhook-certgen:v1.1.1
        imagePullPolicy: IfNotPresent
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
      serviceAccountName: replacer