apiVersion: v1
kind: Service
metadata:
  name: replacer
  labels:
    app: replacer
spec:
  ports:
    - port: 443
      targetPort: 8181
      name: replacer
  type: ClusterIP
  selector:
    app: replacer