apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: replacer
  namespace: lan
  labels:
    app: replacer
webhooks:
  - name: replacer.default.svc
    admissionReviewVersions: ["v1beta1"]
    sideEffects: None
    clientConfig:
      service:
        name: replacer
        namespace: default
        path: "/mutate"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments","daemonset","statefulset"]